### ISSUE TITLE
Build and push Alpine 3.3 image?

### ISSUE THREAD

**Issue by arichiardi** [develar/docker-java#14]
Thanks for maintaining this image, I started using it and it is really serving me well.
I noticed though that the Dockerhub image looks "old", meaning that it does not include Alpine 3.3, which I instead see here.
I was curious whether there is a reason to keep things at 3.1, maybe some Java incompatibility?
I am going to try anyways to use Alpine 3.3 with my apps and report back.
Thanks again!

**Comment by develar** [comment]
Latest is Alpine 3.3, see build log — https://hub.docker.com/r/develar/java/builds/br2h8eysp5szdqmsuex475u/ `Step 1 : FROM alpine:3.3`

**Comment by arichiardi** [comment]
Oh ok, thanks! Maybe only the "show Dockerfile" tab on Docker Hub is showing the wrong thing then!
Closing this :+1:
