### ISSUE TITLE
openssl command broken in alpine:3.3

### ISSUE THREAD

**Issue by grepory** [develar/docker-java#9]
With the upgrade to Alpine 3.3, we now don't have the ability to run or link against OpenSSL in this container. See this issue:

http://forum.alpinelinux.org/forum/general-discussion/error-update-ca-certificates

It appears to be fixed in alpine:edge, but I would not want to suggest upgrading to that. Just wanted to make you aware. I would suggest either moving down to alpine:3.2 or following releases to alpine:3.3 carefully.

**Comment by develar** [comment]
@leodutra What do you think?

**Comment by grepory** [comment]
So, the sad news is that 3.2 is affected now as well. This PR doesn't really fix anything anymore.

**Comment by leodutra** [comment]
@develar We could branch master and create a docker hub tag for alpine:3.2. 

But ... stuff is blown.
